Entry.create(title:"this", author:"alex", body:"Is the most awesome blog post ever.", tags:"Awesome, Blog, Post")
Entry.create(title:"is", author:"alex", body:"Let's do this.", tags:"Awesome, Blog, Post")
Entry.create(title:"truly", author:"alex", body:"Positive Entry.", tags:"Awesome, Blog, Post")
Entry.create(title:"awesome", author:"alex", body:"I'm going to dominate the programming market.", tags:"Awesome, Blog, Post")
Entry.create(title:"z0rz", author:"alex", body:"I'm going to be the best at programming.", tags:"Awesome, Blog, Post")
